# 운영서버 환경설정
spring:
  # 데이터베이스 접속정보 설정
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/profile
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      location: /data/was/fileupload-temp
  mail:
    host: 127.0.0.1
    port: 25
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false
    
logging:
  level: 
    root: info
    '[kr.songjava]': DEBUG
    
# 파일 업로드 관련 설정    
file:
  root-path: /spring-boot-fileupload
  resource-path: /static/image/**
  
# 이메일 서비스 정의
email:
  service: real

frontend:
  domain: http://dev-spring.com:3000












