# 개발서버 프로퍼티 정의
spring:
  datasource:
    username: root
    password: 1234  
    url: jdbc:mariadb://localhost:3306/profile_dev   
  servlet:
    multipart:
      location: /data/was-app/fileupload-temp
  mail:
    host: 127.0.0.1
    port: 25
    #username: 
    #password: 
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false      
# 파일 업로드 관련 설정    
file:
  rootPath: /data/was-app/fileupload
  resourcePath: /static/image/**
email:
  service: real  