# 개발서버 프로퍼티 정의
spring:
  datasource:
    username: root
    password: 1234  
    url: jdbc:mariadb://localhost:3306/profile
  servlet:
    multipart:
      location: /spring-boot-fileupload-temp
# 파일 업로드 관련 설정    
file:
  rootPath: /spring-boot-fileupload
  resourcePath: /static/image/**
 
email:
  service: test